### ISSUE TITLE
squish.py error

### ISSUE THREAD

**Issue by blaboing** [blaboing/Koi#3]
squish throws an error

text snippet in error is from js\koi\fish\pattern\layerFootprint.js

> tmp-in:10413:2: ERROR - [JSC_PARSE_ERROR] Parse error. primary expression expected
>   10413|  * A layer footprint to match a layer to
>            ^
> 
> 1 error(s), 0 warning(s)
> Traceback (most recent call last):
>   File "*\myKoi\squish.py\squish.py", line 205, in <module>
>     Document(args['source']).process(args['target'], sys.argv)
>   File "*\myKoi\squish.py\squish.py", line 33, in process
>     self.__collect((
>   File "*\myKoi\squish.py\squish.py", line 193, in __collect
>     self.__extract_tags([tag[0] for tag in tags], get_match)
>   File "*\myKoi\squish.py\squish.py", line 126, in __extract_tags
>     self.__source = re.sub(self.__make_regex_tag(tags), match, self.__source)
>   File "%appdata%\Local\Programs\Python\Python39\lib\re.py", line 210, in sub
>     return _compile(pattern, flags).sub(repl, string, count)
>   File "*\myKoi\squish.py\squish.py", line 189, in get_match
>     self.__compress(directory, combined[tag], include_tag[tag], css_variables, flags))
>   File "*\myKoi\squish.py\squish.py", line 54, in __compress
>     return compress_js(directory, contents, css_variables, '--advanced-cc' in flags)
>   File "*\myKoi\squish.py\js.py", line 59, in compress_js
>     with open('tmp-out', 'r', encoding="utf8") as file:
> FileNotFoundError: [Errno 2] No such file or directory: 'tmp-out'

**Comment by blaboing** [comment]
fixed
